### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by takukudo** [PML-UCF/pinn_wind_bearing#1]
Hello.
My name is Taku Kudo.
I couldn't find any forum or contact link so ask question in Git issue. Sorry about that.
If this question is not suitable for issue, please delete it.

I read your paper "Wind turbine main bearing fatigue life estimation with physics-informed neural networks" and found true grease degradation data for 4 years in figure 17.
But I couldn't find the data in your dataset link(https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ENNXLZ).
Is the data not opened for public?

And additionally, I want to ask about the method to obtain True value of Bearing damage and grease damage.
I know that grease damage value is obtained in each month period and interpolating them.
But I cant understand how to define the damage value from any observation.

**Comment by YiitAnil** [comment]
Data for long term grease damage propagation is included in the dataset.

About the second question, what we consider as the “actual” degradation for the bearing and grease comes from the life curves provided by manufacturers. For the bearing, SKF catalog provides a life formula for spherical roller bearings (Eq. 3 in our paper), and for grease, Klueber catalog provides life curves for grease as a function of temperature (Fig. 19a in our paper). Eventually, we utilize Palmgren-Miner’s rule to obtain incremental damage at each time step, and then linearly accumulate over time.
